package servlets;

import java.sql.*;
import business.*;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Heather Ward
 */
 

public class HBLogonServlet extends HttpServlet {


    protected void processRequest(HttpServletRequest request,
            HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        
        String URL = "/HBLogon.jsp", msg = "", sql = "", userid = "";
        String passattempt = "";  //reads from logon.jsp (not database)
        User u;
        
	ConnectionPool pool = null;
        Connection conn = null;
        PreparedStatement ps = null;    //preset SQL statement
        ResultSet rs = null;    //use executeQuery() to execute ps & return object generated by query
        
        try {
            //obtain values from form
            userid = request.getParameter("userid").trim();
            passattempt = request.getParameter("password").trim();
            
            //establish connection to db
            pool = ConnectionPool.getInstance();
            conn = pool.getConnection();
            
            ps = conn.prepareStatement("SELECT * FROM users WHERE userID = ?");

            ps.setString(1, userid);
            rs = ps.executeQuery();
			
            if (rs.next()) {
                u = new User();
                u.setUserID(userid);
                u.setPassword(rs.getString("userPassword"));   //fetch actual pw from db
                u.setPassAttempt(passattempt);              //set *attempted* pw
                if (u.isAuthenticated()) {      //if passwords match
                    u.setUserName(rs.getString("userName"));
                    u.setStoreID(rs.getString("storeID"));
                    u.setAdminLevel(rs.getString("adminLevel"));
                    msg += "User " + userid + " authenticated. <br>";
                    URL = "/ViewInventory.jsp";
                } else {
                    msg += "User " + userid + " on file but not authenticated. <br>";
                }
                
                HttpSession session = request.getSession();
                session.setAttribute("u", u);  //store user in session
                //session.setAttribute("adminLevel", u.getAdminLevel());
                
                //set boolean for admin status instead
                session.setAttribute("isAdmin", "Admn".equalsIgnoreCase(u.getAdminLevel()));
            } else {
                msg += "User " + userid + " not found in database.<br>";
            }
            
            //setup dropdown list of stores
            PreparedStatement ps2 = conn.prepareStatement("SELECT * FROM stores ORDER BY StoreName"); //new prepared statement
            ResultSet rs2 = ps2.executeQuery();    //new resultset
            ArrayList<Store> storeList = new ArrayList<>();
            while (rs2.next()) {
                Store store = new Store();
                store.setStoreID(rs2.getInt("StoreID"));
                store.setStoreEmp(rs2.getInt("StoreEmp"));
                store.setStoreName(rs2.getString("StoreName"));
                store.setStoreAddress(rs2.getString("StoreAddr"));
                storeList.add(store);
            }
            request.getSession().setAttribute("storeList", storeList);
            
        } catch (SQLException e) {
            throw new ServletException("Error reading DB", e);
        } finally {
            try {
                if (rs != null) rs.close();
            } catch (SQLException ignored) {    
            }
            try {
                if (ps != null) ps.close();
            } catch (SQLException ignored) {    
            }
            if (conn != null && pool != null) {
                pool.freeConnection(conn);
            }
        }
        
        request.setAttribute("msg", msg);
        Cookie uid = new Cookie("userid", userid);
        uid.setMaxAge(60 * 5);
        uid.setPath("/");
        response.addCookie(uid);
        
        RequestDispatcher disp = getServletContext().getRequestDispatcher(URL);
        disp.forward(request, response);
        
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}